Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  #config.vm.synced_folder ".", "/vagrant", disabled: false

#=============#
#VM_for_webapp#
#=============#

  config.vm.define "server" do |server|
    server.vm.hostname = "qumiraudS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 4
      vb.name = "qumiraudS_VM"
    end

    #execution du script dans la VM Vagrant pour installer K3s et setup les pods#
    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
      
