ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    server.vm.hostname = "Server"
    server.vm.network "private_network", ip: "192.168.56.110"
   
    server.vm.provision "file", source: "~/Inception-of-things/p1/confs/config.yaml", destination: "/tmp/config.yaml"
    server.vm.provision "shell", name: "init-server", path: "./scripts/init-server.sh"
  end

  config.vm.define "worker" do |worker|
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.hostname = "Worker"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provision "shell", name: "init-worker", path: "./scripts/init-worker.sh"
  end
end
